from .bus.messages import ModuleId

class TimerTick:
    """The event raised when the bomb timer ticks."""

class BombWarning:
    """The event raised when a warning-level message is generated by the bomb."""

    __slots__ = ("reason", "module")

    def __init__(self, reason: str, module: ModuleId = None):
        self.reason = reason
        self.module = module

class BombInitFailure:
    """The event raised when the bomb initialization fails."""

    __slots__ = ("reason",)

    def __init__(self, reason: str):
        self.reason = reason
