from enum import Enum


class BombState(Enum):
    UNINITIALIZED = 0
    RESETTING = 1
    DETECTING_MODULES = 2
    INITIALIZING_MODULES = 3
    INITIALIZED = 4
    GAME_STARTING = 5
    GAME_STARTED = 6
    GAME_PAUSED = 7
    DEFUSED = 8
    EXPLODED = 9
    INITIALIZATION_FAILED = -1
    DEINITIALIZED = -2
